import { EngineeringNotebook } from "../../../types";

export const portfolioLogs: EngineeringNotebook = {
  projectId: "portfolio",
  title: "Interactive Portfolio Architecture Logs",
  summary: "Logs detailing WebGL layer isolation, React Portal code-splitting, and camera viewport calculations.",
  decisions: [
    {
      id: "portfolio-portals",
      title: "React Portals Lazy-Loading vs Conditional DOM Rendering",
      context: "Mounting heavy recruiter panels and project explorer modals above full-screen Three.js WebGL layers.",
      reasoning: "React Portals mount overlays outside the root container directly into document.body. This separates click triggers from WebGL canvas hits and allows lazy-loading JS bundles on demand.",
      alternatives: [
        "Inline conditional React divs (causes z-index stacking bugs with Three.js canvas)",
        "Multi-page architecture (reloads WebGL scenes and breaks animation smoothness)"
      ],
      tradeoffs: [
        "Requires dynamic React Suspense boundaries",
        "Requires synchronizing body scroll toggles manually during portals mounting"
      ],
      outcome: "Reduced the initial Javascript bundle size by 24kB and maintained high main page speed scores.",
      category: "Code Splitting",
      tags: ["React Portals", "Lazy Loading", "WebGL Isolation"],
      difficulty: "Medium"
    },
    {
      id: "portfolio-z-index",
      title: "CSS Variables Stacking Scale vs Arbitrary Stacking Scales",
      context: "Managing overlay layers between Three.js, navigation navbar, social icons, and glassmorphic panels.",
      reasoning: "Defining a unified CSS z-index scale (e.g. --z-navbar, --z-overlay, --z-recruiter) in index.css ensures that panels sit on top without competing z-index scale hacks.",
      alternatives: [
        "Inline override z-index scales (leads to layout bugs on browser updates)",
        "Separate stacking contexts (hard to debug and scale across directories)"
      ],
      tradeoffs: [
        "Requires strict class discipline during UI styling overrides",
        "Cannot handle overlays generated by third-party packages if not configured"
      ],
      outcome: "Standardized layering scales and resolved navbar stacking issues.",
      category: "CSS Architecture",
      tags: ["z-index Scale", "CSS Variables", "Layering"],
      difficulty: "Low"
    }
  ]
};
